{% set name = "pythia8" %}
{% set file_version = "8311" %}
{% set version = file_version[0] + "." + file_version[1:] %}
{% set build = 8 %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://gitlab.com/Pythia8/releases/-/archive/pythia{{ file_version }}/releases-pythia{{ file_version }}.tar.gz
  sha256: 6cca3920a89a5e51d259114804f3f4944133c1d3883d3f454162ccd3f3bd3c4d
  patches:
    - patches/0001-fix-cfg_file-setting-in-configure-8.311.patch

build:
  # Prioritize builds with a higher microarch level.
  # microarch_level 4 not supported yet.
  # c.f. https://github.com/conda-forge/microarch-level-feedstock/issues/5
  number: {{ build }}          # [not (unix and x86_64)]
  number: {{ build + 100 }}    # [unix and x86_64 and microarch_level == 1]
  number: {{ build + 300 }}    # [unix and x86_64 and microarch_level == 3]
  skip: true  # [win]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=root
    - pythia8 >={{ version }},<{{ version.split('.')[0] }}.{{ (version.split('.')[1][0]|int) + 1 }}00.0a0
    # Can't use pin_subpackage as X.Y.Z is written as X.YZ

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - x86_64-microarch-level {{ microarch_level }}  # [unix and x86_64]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rsync
    - make
    - sed
  host:
    - python
    - libxcrypt  # [linux and py<39]
    - pybind11
    - lhapdf
    - fastjet-cxx
    - hepmc2
    - hepmc3
    # zlib controlled through https://github.com/conda-forge/conda-forge-pinning-feedstock/
    - zlib
  run:
    - python
    # zlib needed to be compatible with cxx-compiler
    - zlib

test:
  requires:
    - {{ compiler('cxx') }}
    - lhapdf >=6.2
    - fastjet-cxx
    - hepmc2
    - hepmc3
    - make
    - sed
  imports:
    - pythia8
  source_files:
    - examples/Makefile
    - examples/main01.cc
    - examples/main41.cc
    - examples/main42.cc
    - examples/main42.cmnd
    - examples/main43.cc
    - examples/main43.cmnd
    - examples/main44.cc
    - examples/main44.cmnd
    - examples/main45.cc
    - examples/main51.cc
    - examples/main72.cc
    - examples/main81.cc
    - examples/main81.cmnd
    - examples/w+_production_lhc_0.lhe
    - examples/ttbar.lhe
    - examples/ttbar2.lhe
    - examples/wbj_lhef3.lhe

about:
  home: https://pythia.org/
  license: GPL-2.0-only
  license_file: COPYING
  summary: A tool for the generation of events in high-energy collisions
  description: |
    The Pythia program is a standard tool for the generation of events in
    high-energy collisions, comprising a coherent set of physics models for
    the evolution from a few-body hard process to a complex multiparticle
    final state. It contains a library of hard processes, models for initial-
    and final-state parton showers, matching and merging methods between hard
    processes and parton showers, multiparton interactions, beam remnants,
    string fragmentation and particle decays. It also has a set of utilities
    and several interfaces to external programs.
  doc_url: https://pythia.org/
  dev_url: https://gitlab.com/Pythia8/releases

extra:
  recipe-maintainers:
    - chrisburr
    - henryiii
    - ph-ilten
    - matthewfeickert
